services:
  website: # container name
    build: .
    image: ahmaddraie/week-program-system # to solve the image naming issue

    ports:
      - 80:5000
    volumes:
      - dbdata:/app/databases
    restart: unless-stopped   # Auto-restart on failure or reboot
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

  nginx:                           # new reverse-proxy service
    image: nginx:alpine            # lightweight official Nginx image
    depends_on:
      - website                    # start website first
    ports:
      - "8080:80"                     # map host port 80 → nginx port 80 :contentReference[oaicite:1]{index=1}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  dbdata: